version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: family_dining
      MYSQL_USER: family_dining_user
      MYSQL_PASSWORD: securepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/migrations:/docker-entrypoint-initdb.d

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=family_dining
      - DB_USERNAME=family_dining_user
      - DB_PASSWORD=securepassword
    depends_on:
      - mysql
    ports:
      - "8000:80"

  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1

volumes:
  mysql_data: